---
title: "Untitled"
author: "Gage Clawson"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rredlist)
library(tidyverse)
library(dplyr)
library(rgdal)
library(raster)
library(here)
library(ggridges)
library(ggplot2)
library(stringr)
source(here('workflow/R/common.R'))

goal     <- 'spp'
scenario <- 'v2020'

dir_goal <- here('globalprep', goal, scenario)

### goal specific folders and info
dir_anx  <- file.path(dir_M, 'git-annex/globalprep')
dir_setup   <- file.path(dir_goal, '_setup')
dir_goal_anx <- file.path(dir_anx, goal, scenario, 'spp_risk_dists')
dir_goal_anx_countries <- file.path(dir_anx, goal, scenario, 'spp_countries')

source(file.path(dir_setup, 'common_fxns.R'))
```


get all species from iucn 
```{r}
rl_sp_count(key = api_key)

out <- rl_sp(all = TRUE, key = api_key)
all_df <- do.call(rbind, lapply(out, "[[", "result"))

all_df_comp <- all_df %>%
  dplyr::select(-infra_rank, -infra_name) %>%
    dplyr::rename(iucn_sid = taxonid, sciname = scientific_name) %>%
    setNames(names(.) %>%
               stringr::str_replace('_name', ''))

write.csv(all_df_comp, file.path(dir_goal,"raw_test/spp_list_iucn.csv"))
```

get all species habitats from iucn
todo: add api_error column and grab the error

```{r}
spp_ids_all <- all_df_comp %>%
    .$iucn_sid

  n_chunks <- ceiling(unique(spp_ids_all))

for(i in spp_ids_all){
  #i = 43
  
  chunk_file <- file.path(dir_goal, 'tmp', 
                    sprintf('spp_habs_chunk_%s.csv', 
                            i))
  
  if(!file.exists(chunk_file)) {
    
     cat_msg('Getting habitat info for species ', i, ' to ', max(spp_ids_all))
    
spp_hab_tmp <- rl_habitats(id = i, key = api_key)
  
spp_hab_tmp_2 <- data.frame(cbind(id = spp_hab_tmp$id, spp_hab_tmp$result)) %>%
  mutate(param_id = ifelse(is.na(id), i, id))

cat_msg('... found ', nrow(spp_hab_tmp_2), ' habitat rows for these species')

write_csv(spp_hab_tmp_2, chunk_file)
  
}else {
   cat_msg('Chunk file ', chunk_file, ' already exists; skipping these spp')
      
}
}


```


Get US Minor Outlying Islands species 
```{r}
## get a dataframe of all iucn redlist species
out <- rl_sp(all = TRUE, key = api_key)
all_df <- do.call(rbind, lapply(out, "[[", "result"))

all_df_comp <- all_df %>%
  dplyr::select(-infra_rank, -infra_name) %>%
    dplyr::rename(iucn_sid = taxonid, sciname = scientific_name) %>%
    setNames(names(.) %>%
               stringr::str_replace('_name', ''))

library(ohicore)
spp_country_url <- 'http://apiv3.iucnredlist.org/api/v3/country/getspecies/id/%s?token=%s'
# 
# /api/v3/country/getspecies/:country?token='YOUR TOKEN'

rl_countries(key = api_key)
#UM is United States Minor Outlying Islands country code
spp_um <- rl_sp_country('UM', key = api_key)$result %>%
  mutate(country_code = "UM", country = "Palmyra Atoll") %>%
  rename("iucn_sid" = "taxonid")

# join with all_df_comp to get the kingdom,phylum,order, etc
spp_pal <- all_df_comp %>%
  inner_join(spp_um, by = c("iucn_sid", "category")) %>%
  dplyr::select(-scientific_name)

#list of iconic species for palmyra
ico <- c("Sula leucogaster", "Sula dactylatra", "Sula sula", "Anous minutus", "Anous stolidus",
          "Fregata minor", "Onychoprion fuscata", "Numenius tahitiensis", "Pluvialis fulva",
          "Heteroscelus incanus", "Arenaria interpres", "Tursiops aduncus", "Stenella longirostris",
          "Chelonia mydas", "Eretmochelys imbricata", "Tridacna gigas", "Birgus latro")

# Filter the UM spp data for Palmyra iconic spp 
pal_ico <- spp_pal %>% 
  filter(sciname %in% ico) %>% # 11 matching the ico spp list
dplyr::select(-country, -country_code, -subspecies, -rank, -subpopulation)

## Figure out which ones didn't match
setdiff(ico, pal_ico$sciname)

#make vector of those that didn't match
ico_not_listed <- c("Onychoprion fuscata", "Heteroscelus incanus", "Tursiops aduncus", "Eretmochelys imbricata", "Tridacna gigas", "Birgus latro")

## filter overall species list for those that didnt match
pal_ico_not_listed <- all_df_comp %>%
  filter(sciname %in% ico_not_listed) ## now only 2 not matched! 

#Join this with pal_ico
pal_ico_new <-
  rbind(pal_ico_not_listed, pal_ico)
  


rl_threats(name = "Tursiops aduncus", key = api_key)
```

