---
title: "Landbased nutrient and chemical"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(tidyverse)
library(raster)
library(sf)
library(mapview)
library(janitor)


source('../../workflow/R/common.R')

ww_raw_dir <- "/home/shares/ohi/git-annex/land-based/wastewater/data/raw"
ww_intermediate_dir <- "/home/shares/ohi/git-annex/land-based/wastewater/data/interim"
cw_nutrient_int_dir <- "/home/shares/ohi/git-annex/globalprep/cw_nutrient_o_chem/int"

```

Read in watersheds files, transform the CRS to 4326, and bind together to make one file. 
```{r}
## Watersheds; read in, reproject to EPSG 4326, and combine into one file. 


watersheds_af <- st_read(file.path(ww_raw_dir, "basins_laea/af_bas.shp")) %>%
  clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
crs(watersheds_af)
plot(watersheds_af$geometry)
watersheds_af <- st_transform(watersheds_af, 4326)
plot(watersheds_af$geometry)
crs(watersheds_af)
st_write(watersheds_af, file.path(cw_nutrient_int_dir, "watersheds/watersheds_af_4326.shp"))

watersheds_au <- st_read(file.path(ww_raw_dir, "basins_laea/au_bas.shp")) %>%
    clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
plot(watersheds_au$geometry)
watersheds_au <- st_transform(watersheds_au, 4326)
plot(watersheds_au$geometry)
crs(watersheds_au)
st_write(watersheds_au, file.path(cw_nutrient_int_dir, "watersheds/watersheds_au_4326.shp"))

watersheds_eu <- st_read(file.path(ww_raw_dir, "basins_laea/eu_bas.shp")) %>%
    clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
plot(watersheds_eu$geometry)
watersheds_eu <- st_transform(watersheds_eu, 4326) 
crs(watersheds_eu)
st_write(watersheds_eu, file.path(cw_nutrient_int_dir, "watersheds/watersheds_eu_4326.shp"))

watersheds_na <- st_read(file.path(ww_raw_dir, "basins_laea/na_bas.shp")) %>%
    clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
plot(watersheds_na$geometry)
watersheds_na <- st_transform(watersheds_na, 4326) 
plot(watersheds_na$geometry)
crs(watersheds_na)
st_write(watersheds_na, file.path(cw_nutrient_int_dir, "watersheds/watersheds_na_4326.shp"))

watersheds_pa <- st_read(file.path(ww_raw_dir, "basins_laea/pa_bas.shp")) %>%
    clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
plot(watersheds_pa$geometry)
watersheds_pa <- st_transform(watersheds_pa, 4326) 
plot(watersheds_pa$geometry)
crs(watersheds_pa)
st_write(watersheds_pa, file.path(cw_nutrient_int_dir, "watersheds/watersheds_pa_4326.shp"))

watersheds_sa <- st_read(file.path(ww_raw_dir, "basins_laea/sa_bas.shp")) %>%
    clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
plot(watersheds_sa$geometry)
watersheds_sa <- st_transform(watersheds_sa, 4326) 
crs(watersheds_sa)
st_write(watersheds_sa, file.path(cw_nutrient_int_dir, "watersheds/watersheds_sa_4326.shp"))

watersheds_as <- st_read(file.path(ww_raw_dir, "basins_laea/as_bas.shp")) %>%
    clean_names() %>%
  dplyr::select(id, gridcode, area, basin_id)
plot(watersheds_as$geometry)
watersheds_as <- st_transform(watersheds_as, 4326) 
crs(watersheds_as)
st_write(watersheds_as, file.path(cw_nutrient_int_dir, "watersheds/watersheds_as_4326.shp"))

watersheds_all <- rbind(watersheds_eu, watersheds_au, watersheds_na, watersheds_pa, watersheds_af, watersheds_sa, watersheds_as)
plot(watersheds_all$geometry)

st_write(watersheds_all, file.path(cw_nutrient_int_dir, "watersheds/watersheds_all_4326.shp"))

```
Read in pourpoints file and transform crs to be 4326
```{r}
## Pourpoints

global_plume <- st_read("/home/shares/ohi/git-annex/land-based/wastewater/data/raw/pour_points/global_plume_2007_2010.shp")
plot(global_plume$geometry)
mapview(global_plume)

global_plume <- st_transform(global_plume, 4326) 

```

Read in PO4eq fertilizer data and disaggregate by 15 to make higher resolution. 
```{r}
## N/P fertilizer data

n_p_rast <- raster(file.path("/home/shares/ohi/git-annex/globalprep/_raw_data/NCEAS_food_systems/d2020/crop_fert_PO4eq.tif"))
plot(log(n_p_rast + 1))

crs(n_p_rast) 

n_p_rast
plot(area(n_p_rast))

n_p_dis_rast <- disaggregate(n_p_rast, fact = 15, method = '', progress = TRUE)
n_p_dis_rast
plot(n_p_dis_rast)
plot(area(n_p_dis_rast))

#writeRaster(x = n_p_dis_rast, filename = file.path(cw_nutrient_int_dir, "rasters/crop_fert_PO4eq_disagg.tif"), overwrite = TRUE)

n_p_dis_log_rast <- raster::calc(n_p_dis_rast, fun = function(x){log(x + 1)})
#writeRaster(x = n_p_dis_log_rast, filename = file.path(cw_nutrient_int_dir, "rasters/crop_fert_PO4eq_disagg_log.tif"))

plot(n_p_dis_log_rast)
plot(watersheds_all$geometry, add = TRUE)
```

Calculate zonal stats per watershed and save
```{r}
## Zonal stats per watershed 
n_p_dis_rast <- raster::raster(file.path(cw_nutrient_int_dir, "rasters/crop_fert_PO4eq_disagg.tif")) ## read in disaggregated raster

watersheds_all <- st_read(file.path(cw_nutrient_int_dir, "watersheds/watersheds_all_4326.shp")) ## read in watersheds file

wat_length <- length(watersheds_all$basin_id)

watersheds_all <- watersheds_all %>%
  arrange(id) %>%
  mutate(id_new = 1:wat_length) # produce a new id for watersheds so that we can fasterize correctly..


plot(n_p_dis_log_rast)
plot(watersheds_all$geometry, add = TRUE)

# watershed_area <- st_area(watersheds_all)
# sum(watershed_area) # 1.345027e+14 [m^2]

raster_watersheds <- fasterize::fasterize(watersheds_all, n_p_dis_rast, field = "id_new") ## make watershed raster
plot(raster_watersheds)
#writeRaster(x = raster_watersheds, filename = file.path(cw_nutrient_int_dir, "rasters/raster_watersheds.tif"), overwrite = TRUE)

raster_watersheds <- raster::raster(file.path(cw_nutrient_int_dir, "rasters/raster_watersheds.tif"))

zs_n_p <- raster::zonal(n_p_dis_rast, raster_watersheds, fun = 'sum', progress = 'text', na.rm = TRUE) ## calculate sum of PO4eq per watershed
zs_n_p_df <- data.frame(zs_n_p)
#write_csv(zs_n_p_df, "int/zonal_n_p_watersheds.csv")
zs_n_p_df <- read_csv("int/zonal_n_p_watersheds.csv")

#df <- data.frame(n_p = values(n_p_dis_rast))

# df_watershed <- data.frame(id_new = values(raster_watersheds)) %>%
#   filter(id_new > 0 )

#sum(df$n_p) #36282.64; 2351606835
#sum(zs_n_p_df$sum) #36229.26; 2343514672

## the difference here is 8092163. ~ 43 watersheds 

watersheds_all_zs <- watersheds_all %>%
  left_join(zs_n_p_df, by = c("id_new" = "zone")) %>%
  st_join(global_plume, by = "basin_id")

st_write(watersheds_all_zs, file.path(cw_nutrient_int_dir, "watersheds/watersheds_zonal.shp"))

## 43 NAs of sum after joining... 
plot(watersheds_all_zs$sum)

new <- fasterize::fasterize(watersheds_all_zs, n_p_dis_rast, field = "sum") ## fasterize again so that we can plot the "sum" variable.
plot(new)

#writeRaster(new, filename = file.path(cw_nutrient_int_dir, "rasters/zs_raster.tif"))

new_log <- raster::calc(new, fun = function(x){log(x + 1)}) ## take the ln(x+1) so we can plot this better
plot(new_log)
plot(watersheds_all$geometry, add = TRUE)

#writeRaster(new_log, filename = file.path(cw_nutrient_int_dir, "rasters/zs_raster_logged.tif"))
```





